apiVersion: apps/v1 
kind: Deployment
metadata:
  name: backend-deployment
  namespace: wanderlust  
  labels:
    app: backend
spec:
  selector:
    matchLabels:
      app: backend
  replicas: 1
  template:
    metadata:
      name: backend
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: rohit5126/backend:1
          ports:
            - containerPort: 5000

---
apiVersion: v1 
kind: Service
metadata:
  name: backend-service
  namespace: wanderlust
spec:
  selector:
    app: backend
  type: NodePort
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
      nodePort: 31100
